server:
  port: 8098

spring:
  application:
    name: ci-youdu
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8111/eureka/
      
logging:
  file: logs/${spring.application.name}.log
  
youdu:
  address: your.server.address:port
